name: Laura Jontz
favicon: null
layout_spectrum: 1
typography_spectrum: 0.44456
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eef1f6'
    - '#fbdddb'
    - '#2d4c89'
    - '#e87f7e'
    - '#b9c6cf'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
